# Config file for Air

[build]
  # Arbeitsverzeichnis deines Projekts
  # Working directory
  bin = "./tmp/main"            # Das Build-Ziel
  cmd = "go build -o ./tmp/main" # Der Build-Befehl
  # build.args = ["-tags", ""]  # Zusätzliche Build-Argumente
  exclude_dir = ["tmp", "vendor"] # Verzeichnisse, die nicht überwacht werden
  exclude_file = ["air.toml"]   # Dateien, die nicht überwacht werden sollen
  # follow_symlink = true       # Symlinks folgen
  include_ext = ["go", "tpl", "tmpl", "html"] # Dateien, die überwacht werden sollen
  output = "stdout"             # Ausgabeort für Build-Logs
  log = "info"                  # Log-Level (trace, debug, info, warn, error, fatal, panic)

[runner]
  cmd = "./tmp/main"            # Befehl, um die kompilierten Binärdateien auszuführen
  # envs = ["MY_ENV=dev"]       # Zusätzliche Umgebungsvariablen
  watch_delay = 500             # Zeit in Millisekunden zwischen Dateiänderungen und dem Start des Kompilierens
  restart_on_error = true       # Automatisches Neustarten bei einem Fehler
  # kill_signal = "SIGTERM"     # Signal, um den Prozess zu beenden

[log]
  color = "auto"                # Farben verwenden (auto, on, off)
  timestamp = false             # Zeitstempel in Logs

[debug]
  enable = false                # Debug-Modus aktivieren
  bind_addr = "127.0.0.1:0"     # Bind-Adresse für den Debugger

[notify]
  # Befehl, der nach einem erfolgreichen Build ausgeführt wird
  # script = "echo 'Build erfolgreich'"

  # Befehl, der nach einem fehlgeschlagenen Build ausgeführt wird
  # script = "echo 'Build fehlgeschlagen'"

[plugins]
  # Beispiel für ein Plugin, das ausgeführt wird
  # before_build = "before_build_script.sh"
  # after_build = "after_build_script.sh"
